### ISSUE TITLE
assignMission function problems

### ISSUE THREAD

**Issue by tillmas** [tillmas/dcsgroundai#3]
I am trying to get this function to take the inputs, sort the unfriendly target zones by distance from the reference unit, and then push out the n closest.  It is throwing an error right now, and I am having a hard time troubleshooting it.  I think that there must be a simpler way to do it.  Perhaps splitting the function up into attack and defend.

function assignMission(TargetZones,UnfriendlyZones,FriendlyZones,ReferenceUnits,numAttack,numDefend)

	--function will give a commander an attack order and a defend order
	--Unfriendly zones should be the array of unfriendly zones
	--friendly zones should be an array of the friendly zones
	--ReferenceUnit will be where the algorithm starts looking from
	--will return two tables, the attack zone and the defend zone
	
		defZone = {}
		attZone = {}
		local targetFriendly = {}
		local targetUnfriendly = {}
	
	-- this will put all of the target zones into either friendly or unfriendly
	for i=1,table.getn(TargetZones) do
		if table.contains(UnfriendlyZones,TargetZones[i]) == true then
			table.insert(targetUnfriendly,TargetZones[i])
		else
			table.insert(targetFriendly,TargetZones[i])
		end
	end
	--if the number of attacks is more than the number of unfriendly target zones, just return all of them
	
	if table.getn(targetUnfriendly) <= numAttack then
		attZone = targetUnfriendly
	
	else
		-- build a table with the distances between each zone and the reference
		local distances = {}
		
		for j = 1,table.getn(targetUnfriendly) do
			local testCoords = mist.getRandomPointInZone(targetUnfriendly[j],0)
			local refCoords = mist.getAvgPos(ReferenceUnits)
			
			local tempDistance = mist.utils.get2DDist(refCoords, testCoords)
			distances[targetUnfriendly[j]] = tempDistance
		end
		
		--sort the unfriendly zones by distance
		table.sort(distances)
		
		--invert the table to get the sorted index (zone names)
		table.invert(distances)
		
		for k = 1,numAttack do
		
			table.insert(attZone,distances[i])
		end
	end

	if table.getn(targetFriendly) <= numDefend then
		defZone = targetFriendly
	
	else
		-- build a table with the distances between each zone and the reference
		local distances = {}
		
		for j = 1,table.getn(targetFriendly) do
			local testCoords = mist.getRandomPointInZone(targetFriendly[j],0)
			local refCoords = mist.getAvgPos(ReferenceUnit)
			
			local tempDistance = mist.utils.get2DDist(refCoords, testCoords)
			distances[targetFriendly[j]] = tempDistance
		end
		
		--sort the unfriendly zones by distance
		table.sort(distances)
		
		--invert the table to get the sorted index (zone names)
		table.invert(distances)
		
		for k = 1,numDefend do
		
			table.insert(defZone,distances[i])
		end
	end

	return attZone, defZone
end

**Comment by agridenour** [comment]
1. I think the bug you're seeing is caused by ```table.sort(distances)```. ```distances``` appears to be an associative array (of the form { [non-sequential integer key]: value }), so the sort function doesn't know what it's sorting.

Instead the distances array should contain pairs of the form [zoneName, distanceToReferenceUnit], then use the sorting function 

```
function(a, b)
   return a[2] < b[2]
end
```
For a complete example:

**Comment by agridenour** [comment]
Yes, correct. The example I provided needs to be organized. Putting my two examples together results in something like what's shown below. This may not be the correct logic, but it should be (close to) the right overall structure.

-- 1. Zone Control
-- this could be done a little easier/simpler with the included zone handling in MIST
local zonePrefix = "1-" -- string prefix used to select zones 
local numTargetZones = 10 -- set by the mission designer
local zoneList = {} -- list of all zones the script might select as a target
local targetZones = {} -- list of zones selected as targets

--	1a. Get all zones with specified prefix in name
local zoneList = getAllZonesWithPrefix(zonePrefix)

--	1b. Choose zones of interest for the mission
local targetZones = getTargetZones(zoneList, numTargetZones)

-- determine zone states
local attackZones = {}
local defenseZones = {}

-- something that sorts out zones by control status
for z in targetZones do
   if z.controlledBy == "blue" then
       defenseZones[#defenseZones+1] = z.name
   else
       attackZones[#attackZones +1] = z.name
   end
end

-- for each battalion commander...
--    assign attack missions
local attackMissions = assignMission(attackZones, referencePoint, numAttackZones)

--    assign defense missions
local defenseMissions = assignMission(defenseZones, referencePoint, numDefenseZones)

**Comment by tillmas** [comment]
I'm going to close this issue because it has really split into two non-related things.  For now, I replaced the zoneList section of the code with your much better code.  I totally agree with the first half of your design above, I hadn't thought of the need for a prefix or label on the fighting zones to separate them from normal trigger zones - that is a great catch.
