### ISSUE TITLE
Zone Priority Functions

### ISSUE THREAD

**Issue by agridenour** [tillmas/dcsgroundai#4]
- [x] create function to select all zones with a specified prefix
- [x] create function that selects N random zones from a larger list of zones
- [x] create a reference/test mission with zones that include multiple prefixes
- [x] output a complete list of blue and red zones based on prefixes

**Comment by tillmas** [comment]
- [ ] create a reference/test mission with zones that include multiple prefixes

**Comment by tillmas** [comment]
did a bit of editing.  I am going to create an issue for each major function block in the code.

**Comment by tillmas** [comment]
I believe that I have accomplished the first two tasks in the branch for this function (both in the function and then passing the zone prefixes as a table to the function in the main body.

**Comment by tillmas** [comment]
I realized that we could easily address the added fourth task in this function as well.  I wrote this up and pushed it to the branch this morning.

**Comment by tillmas** [comment]
`
-- Returns list of all zones with names containing the prefix [prefix]
function getAllZonesWithPrefix(prefix)
	local list = {}
	for _, z in pairs(mist.DBs.zonesByName) do
	
		-- If zone name starts with specified prefix, add the zone to the list.
		if (string.sub(z.name, 1, #prefix) == prefix) then
			local newZone = z
			local zoneControlPrefix = string.sub(z.name, 1, #prefix + 2)
			
			-- If zone name has the form 'prefixR ', set controlledBy to "Red"
			if (zoneControlPrefix == prefix .. "R ") then
				z["controlledBy"] = "Red"
				
			-- If zone name has the form 'prefixR ', set controlledBy to "Blue"
			elseif (zoneControlPrefix == prefix .. "B ") then
				z["controlledBy"] = "Blue"
		
			-- Otherwise, set controlledBy to "Neutral"
			else
				z["controlledBy"] = "Neutral"
			end

			list[#list+1] = z
		end
	end
	return list
end
`

**Comment by agridenour** [comment]
Considering #5,

Zone tagging could be done in the following way:

```GAI_``` designates the zone for consideration by the ground AI mechanic
```R/B``` designates control 

So an example could be: ```GAI_R FOB Alpha```

Not too different than what we have now. Ideally we just add a property to the zone objects within the getAllZonesWithPrefix function which indicates initial control. Something like the function rewrite below. Note that there are some choices here on the prefix rules. Right now it's ```[prefix]R ```, ```[prefix]B```, or just ```[prefix]``` for Red, Blue, or Neutral zones respectively. Neutral meaning it's considered for ground ai but "controlled" by neither red nor blue.

```
-- Returns list of all zones with names containing the prefix [prefix]
function getAllZonesWithPrefix(prefix)
	local list = {}
	for _, z in pairs(mist.DBs.zonesByName) do
	
		-- If zone name starts with specified prefix, add the zone to the list.
		if (string.sub(z.name, 1, #prefix) == prefix) then
			list[#list+1] = z
		end
	end
	return list
end

-- Adds a "controlledBy" property [values = "Red"/"Blue"/"Neutral"] to zones based on 
--	a special character after the user-specified zone prefix
function queryZoneControlState(zones, prefix)
	local controlledZones = {}
	for i, z in ipairs(zones) do
		local zoneControlPrefix = string.sub(z.name, 1, #prefix + 2)
				
		-- If zone name has the form 'prefixR ', set controlledBy to "Red"
		if (zoneControlPrefix == prefix .. "R ") then
			z["controlledBy"] = "Red"
			
		-- If zone name has the form 'prefixR ', set controlledBy to "Blue"
		elseif (zoneControlPrefix == prefix .. "B ") then
			z["controlledBy"] = "Blue"

		-- Otherwise, set controlledBy to "Neutral"
		else
			z["controlledBy"] = "Neutral"
		end
		controlledZones[#controlledZones + 1] = z
	end
	return controlledZones
end
```
