### ISSUE TITLE
Higher Command Functions

### ISSUE THREAD

**Issue by tillmas** [tillmas/dcsgroundai#6]
- [x] Create a function that assigns M of N zones based on distance from a provided reference
- [x] Perform this task for each AI commander on the Red and Blue sides

**Comment by agridenour** [comment]
Couldn't see if this was addressed anywhere:

- Can multiple commanders (in the same coalition) be assigned the same zone?
- Unless constrained by other factors, do all N zones need to be assigned to commanders? e.g., If there are 5 zones and 3 commanders, and I assigned the same 2 zones to each commander, that leaves 3 unassigned zones. Is that OK?

- Combined question: Should all N zones be allocated to at least one commander before any zone is allocated to more than one commander?

**Comment by tillmas** [comment]
Replying from my phone. Sorry if this doesn’t format well.

Let’s go with No, No, N/A based on the first no.

**Comment by agridenour** [comment]
Thanks.

This is working now. There are three new/completed functions:

```assignMissions``` assigns M of N zones to specified commanders

**Comment by tillmas** [comment]
I just had a thought.  Should we allow the number of total zones selected and the number of zones per commander be user inputs?

**Comment by agridenour** [comment]
Currently it is set up to do just that:

```
local _PREFIX = 'GAZ'

local _NUM_TARGET_ZONES = 5
local _IGNORED_COMMANDERS = {'A'}
local _NUM_ZONES_PER_COMMANDER = 2
```

At this point, all that's left is to make sure we include it in the separate user-input lua, and add documentation for those parameters

**Comment by tillmas** [comment]
OK, you want me to verify this one merge and close?

**Comment by agridenour** [comment]
Yeah I'd say this is ready. I'm working the next one now
