### ISSUE TITLE
Force Structure Functions

### ISSUE THREAD

**Issue by tillmas** [tillmas/dcsgroundai#7]
- [x] Create a function that reads in the force structure of a side based on unit name prefixes
- [x] Have this function output both a list of units for that side as well as a number of AI commanders 
- [x] Have this output differentiate which side a unit is attached to
- [x] Update the DCS test mission to include units named A-1 through D-4.

**Comment by agridenour** [comment]
- How are we deciding the number of AI commanders? By using group/unit name prefixes?

**Comment by tillmas** [comment]
I'm trying to get Wave's perspective on this.  I would like to see a commander be able to command a company made up of four platoons or a battalion made up of four companies.  Either way, I think that each commander has 4 units that they can task.  These four things may have slightly different composition, but I don't think that the algorithm needs to reason over the composition of the units.

For the next iteration of the mission, I will include four units labelled as 'A-1' through 'A-4' to 'D-1' through 'D-4'.

I would also add a line at the top in the mission editor inputs like:
`local commanderPrefixes = {'A','B','C','D'}`

**Comment by tillmas** [comment]
We are diverging a bit in naming conventions, I'm going to put a standard together.

**Comment by tillmas** [comment]
Updated the top tasking to reflect our conversation about units and sides.

**Comment by agridenour** [comment]
All tasks on this Issue are complete. I updated the mission for you to test. If it looks good we're ready to merge

**Comment by tillmas** [comment]
When you tested, did you add the new script to the trigger?  You have to do that every time the script changes in DCS ME.

When I tested, I got an error on line 185, which is the call to the assignMission function.

the error was attempt to index field 'C2' a nil value

**Comment by agridenour** [comment]
Ah good catch yeah.
